### ISSUE TITLE
Ensure that licensing is correct

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#10]
Make sure all License files are correct, make sure there's appropriate POM.xml and Gradle integration, and documentation of how to update that.
Do this for the sister projects too.

**Comment by DanySK** [comment]
Hi Jake,
this is a header proposal, based on the old one:

```java
/*
 * Copyright (C) 2010-2015, Danilo Pianini and contributors
 * listed in the project's build.gradle or pom.xml file.
 * 
 * This file is part of Protelis, and is distributed under the terms of
 * the GNU General Public License, with a linking exception, as described
 * in the file LICENSE.txt in this project's top directory.
 */
```

**Comment by jakebeal** [comment]
This looks like a good header.

**Comment by DanySK** [comment]
Good, we have a header then :)

**Comment by jakebeal** [comment]
Some files, e.g. FieldMapImpl, still say that they are part of Alchemist, not Protelis.  Is this correct?

**Comment by DanySK** [comment]
No, I will review the files one by one. The copyright plugin did not work as expected.

**Comment by DanySK** [comment]
Hi Jake,
as of b3e7880273acee1d2d2e919c306a7d8668a4fed3, all the headers should be ready to go.

Can I release 4.0.0?

**Comment by jakebeal** [comment]
I just set up a pull request to add in a couple of small API enhancements.  They aren't really necessary for 4.0.0, but I think you might as well pull them in before releasing.
