### ISSUE TITLE
Commented-out imports are still imported

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#100]
When I had an invalid import at the top of my file, I attempted to comment it out:

`// import protelis:state:time
`

The file, however, still fails to parse because the import statement is being processed.
This is confirmed by changing the statement:

`// importt protelis:state:time
`

The file now correctly parses and executes.

**Comment by jakebeal** [comment]
Bump: this is still a problem.

**Comment by DanySK** [comment]
This is no longer a problem. If it's ok, I'd like to merge #196 and close this issue.
