### ISSUE TITLE
pmd-eclipse-plugin not compatible with eclipse neon

### ISSUE THREAD

**Issue by eiselesr** [Protelis/Protelis#105]
Documentation suggests downloading the latest Eclipse for Java SE developers which is neon.

**Comment by DanySK** [comment]
Hi, I am currently using it on Neon.2 (4.6.2). Can you install it from [this update site](https://sourceforge.net/projects/pmd/files/pmd-eclipse/update-site/)?

**Comment by DanySK** [comment]
I got no update, I am marking this as solved. Please let me know if this is still a problem.
