### ISSUE TITLE
Memory leak in alignedMap

### ISSUE THREAD

**Issue by w4bo** [Protelis/Protelis#110]
Given
```
def multiInstance(sources, f, null) {
    alignedMap(
        nbr(sources.map(self, id -> {[id, null]})),
        (key, field) -> { true },
        (key, field) -> { f.apply(key) },
        null
    )
}
```
this code causes a memory leak
```
multiInstance(["0"], id -> { nbr(self) }, Infinity)
```
while this doesn't
```
multiInstance(["0"], id -> { nbr(self.getDeviceUID().toString()) }, Infinity)
```
`nbr(self)`, in the restricted domain of `alignedMap`, spreads the new `ExecutionContext`. `ExecutionContext`s aren't removed by GC.

**Comment by w4bo** [comment]
Add files to reproduce memory leak
[nbrself.zip](https://github.com/Protelis/Protelis/files/790302/nbrself.zip)

**Comment by DanySK** [comment]
Solved in the development branch. Change to be rolled out soon in mainline.
