### ISSUE TITLE
Access problems when calling Interface methods

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#116]
When invoking a call on an interface method (e.g., java.util.List.get(int n)), reflection accesses the method on the implementation, rather than the interface.

In many Java utility classes, the implementation is *not* public, e.g., in the lists produced by Arrays.asList.  This causes an exception unless access permissions are overridden (which is done in commit 2e02f3c).  This is not a good practice, however, and it would be better to avoid overriding access permissions.

**Comment by DanySK** [comment]
This makes no sense to me. If a method is declared in an interface, the implementing class can not restrict its visibility. Also, I cannot understand what would it mean to access the method on the interface, since it can't be implemented (except Java 8's default methods, but that's not the case). There is something else going on here.

**Comment by jakebeal** [comment]
This appears to be an issue with Java reflection in general: you get errors like 

> can not access a member of class java.util.Arrays$Arraylist with modifiers "public"

Here is an example of another person running into this problem:

http://stackoverflow.com/questions/25020756/java-lang-illegalaccessexception-can-not-access-a-member-of-class-java-util-col

**Comment by DanySK** [comment]
That occurs when the inner class is not accessible, as `java.util.Arrays$Arraylist` is. This is a behavior of Java that I believe we should not try to work around, but rather use classes the way they are supposed to be used. For this specific case (method08.pt), I'd suggest use Guava libraries in place of Arrays.asList.
