### ISSUE TITLE
ExecutionEnvironment needs a key iterator

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#120]
The ExecutionEnvironment interface needs a way to iterate through the set of defined keys. I have need to do this for implementing a debugging interface, and see no reason why this functionality of maps should be hidden.

**Comment by jakebeal** [comment]
I guess this could be done either at the level of exposing the key-set or at the level providing just an iterator. I think it would probably be better to expose the key-set, as there are useful functions that can be performed with that an iterator would still allow one to access, only awkwardly.

**Comment by DanySK** [comment]
We could expose the key set, provided that it's wrapped onto an `unmodifiableSet`.

**Comment by jakebeal** [comment]
I think that making it unmodifiable would be fine, as long a we put that into the documentation.  We've got ample means of modifying, after all.

**Comment by jakebeal** [comment]
Fixed by #137
