### ISSUE TITLE
flexGradient broken

### ISSUE THREAD

**Issue by w4bo** [Protelis/Protelis#124]
`flexGradient` returns `-Infinity` in case a device whose distance from a source is < `Infinity` and has no neighbors.
```
def flex_slope(d, minD, metric) {
    maxHood([(d - nbr(d)) / flex_distorce(minD, metric), nbr(d), flex_distorce(minD, metric)])
    // in case of no neighbors returns [Infinity, -Infinity, X]
}
public def flexGradientWithMetric(source, epsilon, rate, range, distortion, metric) {
    rep (d <- Infinity) { // assume: d < Infinity
        mux (source) { 0 } // device is not a source
        else {
            let dist = range * distortion; // whatever
            let slope = flex_slope(d, dist, metric); // [Infinity, -Infinity, X]
            let ct = minHood(nbr(d) + flex_distorce(dist, metric)); // Infinity
            if (d == ct || (d > range && d > ct * 2) || cyclicTimer(rate)) { // assume cyclicTimer(rate) false
                ct
            } else {
                if (slope.get(0) > (1 + epsilon)) { // Infinity > 1 + epsilon
                    slope.get(1) + slope.get(2) * (1 + epsilon) // -Infinity + X * (1 + epsilon)
                } else { /* ... */ }
            }
        }
    }
}
```
How do we tackle this problem? What should the device return in this case?

**Comment by w4bo** [comment]
@jakebeal in my opinion this could be a suitable solution
```
if (slope.get(1) == -Infinity || d == ct || (d > range && d > ct * 2) || cyclicTimer(rate)) { ...
```
In this way, a device with no neighbors returns `Infinity` (unless the device is a source)

**Comment by jakebeal** [comment]
I believe that this is a bug in either the implementation of the algorithm or in the Protelis implementation of maxHood for tuples. The prior implementation of the algorithm returns infinity in this case.  I am not sure why the maxHood in flex_slope is returning the -Infinity in there.

**Comment by w4bo** [comment]
In my opinion, it is due to the Protelis default value of `maxHood(nbr(d))` in case of no neighbors (`-Infinity`) rather than on the algorithm - on the other hand, `minHood(nbr(d))` returns `Infinity`.

**Comment by jakebeal** [comment]
maxHood should be returning [-Infinity, -Infinity, -Infinity] for a 3-tuple maxHood with no neighbors.

**Comment by DanySK** [comment]
I believe that is already the case. @w4bo has a test where we try  `maxHood(nbr([0, 0])` with no neighbors, and it correctly returns `[-Infinity, -Infinity]`. The problem is with more complex data structures: `maxHood(nbr([0, ["foo", "bar"]])` would default to `[-Infinity, -Infinity]`.

**Comment by w4bo** [comment]
My bad, `maxHood` returns `[-Infinity, -Infinity, -Infinity]`.

The problem is here: 
```
if (slope.get(0) < (1 - epsilon)) { // true
     slope.get(1) + slope.get(2) * (1 - epsilon) // returns -Infinity
} else { d }
```

**Comment by jakebeal** [comment]
Ah.  And I see the difference... in the Proto implementation, if there are no neighbors, it deliberately returns a different value: [-Infinity Infinity 0]

You can implement this as:

def flex_slope(d, minD, metric) {
   max(maxHood([(d - nbr(d)) / flex_distorce(minD, metric), nbr(d), flex_distorce(minD, metric)]),[-Infinity, Infinity, 0])
}

**Comment by w4bo** [comment]
This is now closed
