### ISSUE TITLE
foldUnion without local value

### ISSUE THREAD

**Issue by DenGuzawr22** [Protelis/Protelis#1241]
What base value I should use in `foldUnion(baseValue, nbr(target))` to have an union without local value?

I tired `foldUnion([], nbr(target))` but it returns an empty list.

**Comment by DanySK** [comment]
what type is `target`? Is it a tuple? Your approach looks correct, you are accumulating starting on an empty tuple and discarding the local value.

**Comment by DenGuzawr22** [comment]
After some additional controls I understand that the list was empty because of communication delay. It seems works correctly.
