### ISSUE TITLE
Javadoc link is broken

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#125]
When I click on the javadoc link it sends me to http://137.204.107.70/protelis-build/protelis/build/docs/javadoc/ which gives me an address unreachable response.

I also do not see the javadoc on maven central. Perhaps I'm just missing it.

**Comment by DanySK** [comment]
Hi, please refer to [this website](http://protelis-doc.surge.sh/) for the latest stable javadoc, and to [this one](http://protelis-unstable-doc.surge.sh/) for the latest develop.
Older versions javadocs get archived automatically on [javadoc.io](https://www.javadoc.io/doc/org.protelis/protelis/).

Would you please point me the file or website where you picked that address from?

Thanks

**Comment by jschewebbn** [comment]
Thank you. Those links work well.

The link I picked up is here: https://github.com/Protelis/Protelis

**Comment by DanySK** [comment]
The `README.md` has been fixed on `master`. Thank you for your report.
