### ISSUE TITLE
IllegalStateException when using molecule without concentration

### ISSUE THREAD

**Issue by Piero93** [Protelis/Protelis#135]
When using a molecule and concentration line is missing or has an empty value or a null value the program crashes throwing an IllegalStateException.

**Comment by DanySK** [comment]
This boils down to calling the ProtelisLoader and passing an empty string. It would bind to the current folder, and comply that's not a file. We need a separate catch clause there for dealing with this case, or - probably better - a check that the String is not empty (or null).

**Comment by DanySK** [comment]
Solved on develop. Will be included in the next Protelis release (and incorporated in Alchemist on the first Alchemist release after that).
