### ISSUE TITLE
Testing platform for nbr

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#14]
Current language testing does not properly test for nbr. Tests in simulator are performed with Alchemist on a separate project, but proper testing of nbr() calls should be in place also here.

**Comment by jakebeal** [comment]
The new Protelis-Demo project has a minimal network implementation that might be used for this.

**Comment by DanySK** [comment]
This has been masterfully solved by @w4bo upon the creation of protelis-lang
