### ISSUE TITLE
S behavior is not self-stabilizing

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#142]
This patch should be applied ASAP

```groovy
def distanceCompetition(d, lead, uid, grain, metric) {
   mux (d > grain) {
       uid
   } else {
       let thr = 0.25 * grain;
       mux (d >= thr) {
           default()
       } else {
           mux (d >= thr) {
               default()
           } else {
               minHood PlusSelf(nbr(lead))
           }
       }
   }
}
```

However, this implementation still has issues when the grain size gets near the communication range.

**Comment by jakebeal** [comment]
Is this issue considered fixed now, or do we want to leave it open for the longer-term study of small grain size issues?

**Comment by DanySK** [comment]
I  merged @w4bo 's pull request, I'd say to close this issue and open a new one for the new problem.
