### ISSUE TITLE
Stack traces do not identify Protelis source lines

### ISSUE THREAD

**Issue by ssclark** [Protelis/Protelis#145]
The current debugging model appears to be limited to looking for where Java choked on the Protelis interpreter and working back based on that exception. Having stack traces that identify the line of Protelis source that triggered the exception would be a major improvement.

**Comment by DanySK** [comment]
I found a way to report Protelis source lines in errors. However, we have a strategic decision here.
I can just track the location of the error, or I can tackle this more deeply and provide something more similar to a Protelis stacktrace to be reported along with the Java one in case of runtime issues.

Of course the second requires more time, but my feeling is that debugging could be eased (and more information could be attached while walking up the abstract syntax tree).

**Comment by jakebeal** [comment]
Can we do both? i.e., the quick fix now and open another deeper issue for the Protelis stack trace?

**Comment by DanySK** [comment]
Yes in general, but at a price: I need to refactor a large part (in terms of classes and lines, not complexity) of the interpreter to put the information in our runtime entities.
Doing it now in a way that allows for supporting full-fledged stracktraces in future is more costly (in time) than just hacking in the minimum required for reporting the line number.
On the other hand, doing the complete work in future over a structure not designed for it would require another refactor as big as the first.

A hybrid solution would be to refactor once, and delay the full stacktrace implementation to the future. It' still closer in time to the second option, though.

**Comment by jakebeal** [comment]
Well, make your call on what you think is best for now, then.

**Comment by DanySK** [comment]
PR #193 provides an implementation of Protelis stack traces.

**Comment by jakebeal** [comment]
Enhancements we are discussing:

- Change from reporting only the line of error to reporting the lines of the construct (e.g., nbr(sin) reported as 7-9 rather than 8)
- Change from reporting `hood` rather than `minHood`
- Can we get a file name on all the lines, and not just the functions?

**Comment by DanySK** [comment]
The former two comments have been addressed:
```
org.protelis.lang.ProtelisRuntimeException: argument type mismatch: cannot invoke public static double java.lang.Math.sin(double) with arguments (I'm definitely not a number.: String)
	at errorTrace02:rootError at line number 8
	at errorTrace02:aCall at line number 14
	at errorTrace02:anotherCall between lines 20 and 22
Fully detailed interpreter trace:
org.protelis.lang.ProtelisRuntimeException: argument type mismatch: cannot invoke public static double java.lang.Math.sin(double) with arguments (I'm definitely not a number.: String)
	at: sin(I'm definitely not a number.) at line number 8
	at: nbr(sin) between lines 7 and 9
	at: minHood(nbr) between lines 6 and 10
	at: rep (x <- 1.0) { minHood } between lines 5 and 11
	at: errorTrace02:rootError(){ rep } at line number 14
	at: nbr(errorTrace02:rootError) at line number 14
	at: errorTrace02:aCall(){ nbr } at line number 22
	at: errorTrace02:anotherCall(){ +; errorTrace02:aCall } at line number 28
```

**Comment by DanySK** [comment]
I opened a new issue for discussing and tracking progress on the latter point: #194. I'm closing this as #193 has been merged to develop.
