### ISSUE TITLE
isRecentEvent defaults to true

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#147]
According to the definition, `isRecentEvent` should return: `true if the event occurred before timeout, false otherwise`. However, with the current implementation:
```
public def isRecentEvent(event, timeout) {
    if (event) {
        true
    } else {
        countDown(timeout) > 0
    }
}
```

`true` is returned even if invoked with `false` for the first `timeout` interval.

**Comment by DanySK** [comment]
Here is a possible solution, but looks kludgy to me:
```
public def isRecentEvent(event, timeout) {
	if (rep(hasHappenedBefore <- false) { hasHappenedBefore || event } ) {
	    if (event) {
	        true
	    } else {
	        countDown(timeout) > 0
	    }
	} else {
		false
	}
}
```

**Comment by jakebeal** [comment]
I think it's a fine solution.
