### ISSUE TITLE
Access to Protelis language reference? 

### ISSUE THREAD

**Issue by cmaclell** [Protelis/Protelis#151]
hello! I'm trying to play around with Protelis and I was wondering if there is a language reference somewhere that I could use? 

I've been reading through the tutorial here: http://proto.bbn.com/webproto/tutorial.html, which refers to the "language reference" documentation. I realize proto is not the same as Protelis, but I'm trying to wrap my head around the computational medium concept.

Thanks!

Chris

**Comment by jakebeal** [comment]
I think the best starting point for wrapping your head around the concepts would be the Demos page on the Protelis website: http://protelis.github.io/
These are taking from various publications and include snippets of code (though some might have some bit-rot, depending on age).

You may also find value in browsing the contents of the protelis-lang library, which has lots of "building block" functions at various levels of abstraction: https://github.com/Protelis/Protelis/tree/master/protelis/protelis-lang/src/main/protelis/protelis

Finally, the JavaDoc for Protelis provides an effective reference document for the hosting of the Protelis VM into Java.  A copy of it is compiled and shared here: http://protelis-doc.surge.sh/

**Comment by cmaclell** [comment]
Excellent, thank you much!

**Comment by DanySK** [comment]
Hi @cmaclell, can we close this issue? Is @jakebeal's answer satisfactory?
