### ISSUE TITLE
ReflectionUtils.invokeMethod should state static methods clearly

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#165]
Currently, if an invocation problem happens with a static method, one is left to guess this from seeing that the invocation target was object "null". We _know_ it's a static method, though, and thus should change the error method to state this explicitly.

**Comment by DanySK** [comment]
I'm currently changing the way it's reported and adding a test. The error will now look like:
```
Cannot invoke public static double java.lang.Math.log(double) with arguments (this is unexpected.: String)
java.lang.IllegalArgumentException: argument type mismatch
```

**Comment by DanySK** [comment]
Protelis 11.0.0-beta+15t.5d5f includes the fix.
