### ISSUE TITLE
Problems using gradle 5.3

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#170]
I'm using Protelis 10.7.0 and trying to upgrade my project's version of gradle from 4.0 to 5.3. I did find that I needed to add the following to my dependencies for everything to compile.
```
implementation group: "org.danilopianini", name: "javalib", version: "5.0.0"                                                                       
implementation group: "org.apache.commons", name: "commons-lang3", version: "3.8.1"   
```

However when I run a test I get the stack trace in the attached log. I expect I'm missing some dependency for xtext that I used to get transitively with gradle 4.0. Do you have suggestions as to what I might be missing?

[build.gradle-5.3_only.log](https://github.com/Protelis/Protelis/files/3022781/build.gradle-5.3_only.log)

My build.gradle file is below. I have
```
import org.gradle.internal.os.OperatingSystem

buildscript {
  repositories {
      mavenCentral()
      jcenter()
  }
}

// Plugins
plugins {
    id 'java'
    id 'maven'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'checkstyle'
    id 'findbugs'
    id "com.github.ben-manes.versions" version "0.21.0"
}


group = 'com.bbn.protelis'
version = '6.1.0'

description = """Protelis Testbed"""

sourceCompatibility = 1.8
targetCompatibility = 1.8
tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}

repositories {
  // local repository first
  mavenLocal()
  
  jcenter()
}

ext {
    jackson_version = "2.9.8"
    log4j_version = '2.11.2'
}

dependencies {
    implementation group: 'com.cedarsoftware', name: 'json-io', version:'4.10.1'
    implementation group: 'com.google.guava', name: 'guava', version:'27.1-jre'
    implementation(group: 'org.protelis', name: 'protelis', version:'10.7.0') {
        exclude(module: 'guava')
    }
    implementation group: 'commons-cli', name: 'commons-cli', version:'1.4'
    implementation group: 'net.sf.jung', name: 'jung-graph-impl', version:'2.0.1'
    implementation group: 'net.sf.jung', name: 'jung-algorithms', version:'2.0.1'
    implementation group: 'net.sf.jung', name: 'jung-visualization', version:'2.0.1'
    implementation group: 'org.slf4j', name: 'slf4j-api', version:'1.7.26'
    runtimeOnly group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: project.log4j_version
    runtimeOnly group: 'org.apache.logging.log4j', name: 'log4j-core', version: project.log4j_version
    testImplementation( group: 'junit', name: 'junit', version: '4.12') {
        exclude module: 'hamcrest-core'
    }
    testImplementation group: 'org.hamcrest', name: 'hamcrest-library', version:'2.1'
    
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: project.jackson_version
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-guava', version: project.jackson_version
    implementation group: 'com.fasterxml.jackson.module', name: 'jackson-module-parameter-names', version: project.jackson_version
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jdk8', version: project.jackson_version
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: project.jackson_version
    
    implementation group: 'dnsjava', name: 'dnsjava', version: '2.1.8'      
    
    implementation group: "org.danilopianini", name: "javalib", version: "5.0.0"
    
    implementation group: "org.apache.commons", name: "commons-lang3", version: "3.8.1"
}

eclipse {
    classpath {
        downloadSources = true
        downloadJavadoc = true
    }
}

checkstyle {
    config = resources.text.fromFile('style.xml', 'UTF-8')
    showViolations = true
    ignoreFailures = false
    toolVersion = "8.10"
}

test {
    testLogging.showStandardStreams = true
    ignoreFailures Boolean.getBoolean("test.ignoreFailures")        
}

findbugs {
    ignoreFailures = true
}

task sourceJar(type: Jar) {
  classifier "sources"
  from sourceSets.main.allJava
}

publishing {
    repositories {
        mavenLocal()
    }
    
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact tasks.sourceJar
        }
    }
}

dependencyUpdates.resolutionStrategy {
    componentSelection { rules ->
        rules.all { ComponentSelection selection ->
            boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm', 'preview', 'b', 'ea'].any { qualifier ->
                selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-+]*/
            }
            if (rejected) {
               selection.reject('Release candidate')
            }
        }
    }
}

```

**Comment by DanySK** [comment]
Some suggestions, and some questions.

* Which JVM are you running Gradle with?
* Could you also attach the output of `./gradlew dependencies --configuration runtime`?
* 4.0 to 5.3 is quite a big jump, which may introduce multiple errors at once, making it harder to find and solve the root causes. My suggestion would be to try switching to 4.10.2 first, once that works, jump to 5.1, and only then upgrade to 5.3. This might be not the case, but often gradual upgrades may help to divide-et-impera the problem. You can set the Gradle wrapper version with a CLI option.

**Comment by jschewebbn** [comment]
Java 8 OpenJDK.

The new command is "--configuration runtimeOnly"

I did the jump from 4.0 to 5.3 on another project and didn't have any issues. I'll try the 4.10.2 upgrade first.
[runtime-deps.log](https://github.com/Protelis/Protelis/files/3023064/runtime-deps.log)

**Comment by DanySK** [comment]
We can exclude issues due to the new Java module system then, which is good.

`--configuration runtimeOnly` actually prints only the dependencies which are going to be present at runtime but not at compile time. `runtime` may be deprecated, but it should be still working, and should print a very long tree, as it includes all the dependencies that are brought when the project is executed.

Otherwise, can you please try `runtimeClasspath`?

Aye, I also painlessly switched to the latest Gradle most of my projects flawlessly, unfortunately some of the biggest and with some exotic dependency management failed and had to debug (actually a couple of them are hard to port to the latest Gradle and are still stuck to 4.10.2, waiting for me to find some time).

**Comment by jschewebbn** [comment]
[runtime.log](https://github.com/Protelis/Protelis/files/3023143/runtime.log)
[runtimeClasspath.log](https://github.com/Protelis/Protelis/files/3023144/runtimeClasspath.log)

**Comment by jschewebbn** [comment]
I just verified that the test problem occurs when upgrading from 4.10.2 to 5.1.

**Comment by DanySK** [comment]
Thanks. I can see no obvious error in your runtime classpath.
OK, so there must be something different, likely in the dependency resolution, with the newer Gradle.
Did you try the [Gradle upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_4.html) from 4.x to 5.x already?

**Comment by jschewebbn** [comment]
Yes, I suspect it's something with the dependency resolution that I'm missing.

**Comment by jschewebbn** [comment]
I checked the runtimeClasspath for both 4.10.2 and 5.1 and the differences are only additions in 5.1.

**Comment by DanySK** [comment]
This is very, very puzzling :|
Can you post both the runtime classpaths' dependency resolutions?
I wonder if something enters the classpath that is an addition but messes up everything, e.g. two jars with the same class entering the classpath, with one shadowing the other.

**Comment by jschewebbn** [comment]
[gradle-4.10.classpath.log](https://github.com/Protelis/Protelis/files/3023397/gradle-4.10.classpath.log)
[gradle-5.1.classpath.log](https://github.com/Protelis/Protelis/files/3023398/gradle-5.1.classpath.log)

**Comment by DanySK** [comment]
Thanks @jschewebbn 
I might have intercepted the issue. Gradle 5.1 pulls in `org.ow2.asm:asm-debug-all:5.0.2` as additional dependency of `com.google.code.findbugs:findbugs:[3.0.0, 3.0.1] -> 3.0.1`. If this jar enters the classpath along with `org.ow2.asm` and goes in front, may shadow some updated classes which are required for Protelis.

This is super subtle and the Xtext error is absolutely unclear, so I might be wrong. Can you try to explicitly exclude `org.ow2.asm:asm-debug-all` and see if it helps?

Also, I believe we should update findbugs to spotbugs and take some action to prevent this kind of configuration issue to happen at all for newer Protelis and Gradle. I'm opening a new issue about that.

**Comment by jschewebbn** [comment]
Thanks, it works now. That's a pretty nasty issue. I'll need to watch that in my other projects since I still use findbugs in them as well.
