### ISSUE TITLE
Non `PlusSelf` hood operations should have mandatory default/base

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#172]
Currently, when something like `minHood(nbr(something))` is called, the interpreter is left alone finguring out the type of the field content, and producing a default value. This produces some unwanted behaviours (like tuples of the wrong size being produced) when a field containing just self is reduced.

Looking at the approach of other functional languages, the way the problem is dealt with is by either providing a monadic `Option` type as result, or by forcing a base value to be specified.
Now, `Option` works particularly well for languages having some sort of pattern matching over algebraic data types (like Scala's `match` or Kotlin's `when`), while in Protelis, unless we add new mechanics, we would have to rely on Java interoperability.
I believe the most straightforward solution for us is to force a manual base value into non-`PlusSelf` hood operations. This would give the programmer control over default values, allowing for consistency of type and structure. 

This is also related to #75, I believe we should discuss the issue, take a stance, and solve both issues at once.

**Comment by jakebeal** [comment]
Superseded by plan in #75
