### ISSUE TITLE
Strengthen our build automation

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#175]
Our build was devised to play well with Gradle 2, which had its own set of caveats to deal with, and it is showing the signs of time passing when used in projects relying on newer build systems. Bugs #170, #173, and #174 seem to be all related to some sort of "build rot".

I propose to tackle this at the root, rather than working it around with patches, by:

1. Incapsulating the behaviour currently exposed by `build-commons` within a number of separate Gradle plugins, which can be developed using the most recent techniques and API, and maintained separately, thus easing maintenance (and, also, making them reusable for other projects as well)
2. Upgrading Gradle to the latest
3. Switching to the [Kotlin Gradle DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html), which is likely to replace in most cases the Groovy DSL we are using right now.

**Comment by jakebeal** [comment]
@DanySK Is this now complete, per #199?

**Comment by DanySK** [comment]
Still missing:
* Switch to modern Kotlin Gradle DSL
* Replace deprecated build-commons plugin with appropriate replacements to be identified
* Force failure on transitive dependency conflicts and solve them manually

**Comment by jakebeal** [comment]
Remaining:
- Switch to Gradle 5.4.1
- Ensure builds can happen on MacOS

**Comment by DanySK** [comment]
Completed by #224.
