### ISSUE TITLE
Eclipse plugin errors do not match execution errors

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#176]
The Eclipse plugin seems to often reports errors that do not exist in execution. These are often related to linking to definitions.

**Comment by jakebeal** [comment]
A current live example:

With the most recent plugin from Eclipse markeplace, Protelis 12.1, and a fresh build in Eclipse Version: 2018-12 (4.10.0), I get 231 errors from the plugin but no failures in running the JUnit tests.

Some sample errors:
```
Description	Resource	Path	Location	Type
Couldn't resolve reference to EObject 'Infinity'.	TupleReduce01.pt	/protelis-test/bin	line: 2 /protelis-test/bin/TupleReduce01.pt	Protelis Problem
Description	Resource	Path	Location	Type
Couldn't resolve reference to EObject 'pi'.	lambda03.pt	/protelis-test/bin	line: 7 /protelis-test/bin/lambda03.pt	Protelis Problem
Description	Resource	Path	Location	Type
extraneous input ';' expecting '}'	function04.pt	/protelis-test/src/test/resources	line: 24 /protelis-test/src/test/resources/function04.pt	Protelis Problem
Description	Resource	Path	Location	Type
extraneous input ';' expecting EOF	fieldMethod03.pt	/protelis-test/src/test/resources	line: 5 /protelis-test/src/test/resources/fieldMethod03.pt	Protelis Problem
```

All errors are of these four classes.

**Comment by DanySK** [comment]
Can you provide the steps you followed for cloning and importing?

**Comment by jakebeal** [comment]
I had a copy of the Protelis repo, and I checked out tag 12.1.  I imported existing projects into a clean Eclipse workspace, then did "Gradle refresh" to get them to build.

**Comment by DanySK** [comment]
Thanks. Do the issues persist if you checkout develop?

**Comment by jschewebbn** [comment]
I just upgraded to the version of the Eclipse plugin in the repository. 99% of my errors in the file below went away. This is good. There is one error left on the first line of the function NewS. The error is "no viable alternative at input 'let'". 

```
module protelis:com:bbn:map:common

import protelis:coord:sparsechoice
import protelis:coord:accumulation
import protelis:coord:spreading
import protelis:coord:meta
import protelis:lang:utils
import protelis:coord:nonselfstabilizing:accumulation
import protelis:state:nonselfstabilizing:time
import protelis:state:time

// Deprecated --> will be included in a future Protelis release
public def once(f) {
    rep (v <- f.apply()) { v }
}


public def union(a, b) {
    a.union(b)
}

public def regionSet(potential) {
    C(potential, union, unionHood(nbr([self.getDevice().getRegionIdentifier()])), [])
}

public def countNodes() {
    let nonce = once(() -> {self.getDevice().nextRandomDouble()});
    let leader = nonce == gossip(nonce, min);
    //self.getDevice().getExecutionEnvironment().put("blue",leader);
    self.getDevice().setRunRLG(leader);
    let d = hopDistanceTo(leader);
    countDevices(d)
}

public def findNeighborRegions(leader) {
    let rgn = self.getDevice().getRegionIdentifier();
    let localNbrRgns = unionHood PlusSelf(nbr([rgn]));
    let localNbrs = unionHood PlusSelf(nbr([self.getDevice().getNodeIdentifier()]));
    self.getDevice().apTraceMessage("findNeighborRegions: localNbrs" + localNbrs);
    
    self.getDevice().apTraceMessage("findNeighborRegions local: " + rgn + " nbrs " + localNbrRgns);
    multiRegion(rgn,(n) -> { rgn == n },
        () -> { 
            let collected = C(hopDistanceTo(leader), union, localNbrRgns, []);
            let sent = hopBroadcast(leader,collected);
            self.getDevice().apTraceMessage("findNeighborRegions internal: " + rgn + " collected " + collected + " sent " + sent);
            sent
         }, [])
}

def randomUid() {
    rep (v <- self.nextRandomDouble()) {
        v
    }
}

public def NewS(diameter, kL, kA) {
let sigma = randomUid();  // make the index of each node fixed
let temp_sigma = sigma;

rep (dbar_sigma <- [0,temp_sigma]) {
 let V_raw = nbr(dbar_sigma);
 

 let V_set_kL = mux(V_raw.get(0) <= kL*diameter) {[V_raw.get(0),V_raw.get(1)]} else {[Infinity,V_raw.get(1)]};
 let M_set_kL = mux(V_set_kL.get(1) < sigma) {[V_set_kL.get(0),V_set_kL.get(1)]} else {[Infinity,V_set_kL.get(1)]};

 let V_set_kA = mux(V_raw.get(0) > kL*diameter && V_raw.get(0) <= kA*diameter) {[V_raw.get(0),V_raw.get(1)]} else {[Infinity,V_raw.get(1)]};
 let M_set_kA = mux(V_set_kA.get(1) < sigma) {[V_set_kA.get(0),V_set_kA.get(1)]} else {[Infinity,V_set_kA.get(1)]};



 let minTuple_kL = minHood([M_set_kL.get(1), M_set_kL.get(0)]);
 let minTuple_kA = minHood([M_set_kA.get(1), M_set_kA.get(0)]);

 mux(minTuple_kL.get(1)+1 < Infinity)
 {
 [minTuple_kL.get(1)+1, minTuple_kL.get(0)];
 }
 else
 {
 mux(minTuple_kA.get(1)+1 < Infinity)
 {
 [minTuple_kA.get(1)+1, minTuple_kA.get(0)];
 }
 else
 {
 [0,sigma];
 };
 }
}.get(0) == 0
}
    



public def electLeader() {
  rep(state <- [true, 0, 1, 2]) {
    let leader = state.get(0);
    let distanceToLeader = state.get(1);
    let estimatedDiameter = state.get(2);
    let newDistance = hopDistanceTo(leader);
    let timers = state.get(3);
    let newDiameter = hopBroadcast(leader, cMultiMax(newDistance+1, maxHood PlusSelf(nbr(newDistance+1))));
    if (newDiameter >= estimatedDiameter)
    { 
     timers = 2;
    }
    else{
    if ( timers >= 1 )
    {
      newDiameter = estimatedDiameter;
      timers = countDownWithDecay(2,1);
    }
    else
      timers = 2;
    };
    };
    //let k = 12;
    let newLeader = NewS(newDiameter,3,12);
    //let newLeader = S(newDiameter*k, ()->{1});
    self.getDevice().apTraceMessage("newDiameter: " + newDiameter + " newDistanceToLeader: " + newDistance + " newLeader: " + newLeader + " timer " + timers);
    [newLeader, newDistance, newDiameter,timers];
  }.get(0);
}

```

**Comment by jschewebbn** [comment]
I'm also finding issues with this function
```
def broadcastObjectToRegion(rgn, isLeader, obj) {
    self.getDevice().apTraceMessage("Sending object to all nodes: " + obj + " leader: " + isLeader);
    multiRegion(rgn,(n) -> { rgn == n },
        () -> { 
            hopBroadcast(isLeader, obj);
        },
        obj)
}
```

At the end of the first line I have "mismatched input ';' expecting '}'". This is also the case at the end of hopBroadcast. Executing this code runs without error.

I also have "Couldn't resolve reference to EObject 'rgn'." and the same for "obj" and "isLeader". 

At the end of the function I have "missing EOF at '}'".

**Comment by jakebeal** [comment]
I'm getting the same problem in `develop`

**Comment by DanySK** [comment]
@jschewebbn remove colons from these lines:
```
[minTuple_kL.get(1)+1, minTuple_kL.get(0)];
```
```
 [minTuple_kA.get(1)+1, minTuple_kA.get(0)];
```

Unfortunately these errors are rather hard to intercept, as the parser does not really know what are the intentions of the programmer, and fails when it finds that an expression is missing, returning an error at the previous instruction.

**Comment by jschewebbn** [comment]
@DanySK does that mean that my Protelis code has not been executing as expected or that the Eclipse parser is checking for different syntax than the parser used to execute the Protelis code?

**Comment by DanySK** [comment]
If the code was executing, then the version of the parser used in that runtime was interpreting the code "as expected". There was probably a mismatch between such version and the Eclipse plugin, if the latter is more recent, it may detect errors that are not errors for a previous version, or accept code that is not acceptable in previous versions.

**Comment by jschewebbn** [comment]
I just upgraded eclipse to 2019-06 and grabbed the latest Protelis plugin to ensure that everything is up to date. I removed those semicolons and I'm still getting "no viable alternative at input 'let'" on the first line of the function "NewS".

I also still have the errors in "brodcastObjectToRegion" from my previous comment.

**Comment by DanySK** [comment]
These errors are usually semicolon-related. Can you attach the file? By passing though, i noticed two more semicolons that should not be there, on consecutive lines:
```
 [0,sigma];
 };
```
thanks

**Comment by jschewebbn** [comment]
OK, removing those semicolons got rid of the let error. Now I'm getting an error about cannot resolve reference to Infinity. 

I'm also getting an error on the first let statement of electLeader.

I've attached the files here, resourcetracker.pt references common.pt. I've renamed the files so that github allows me to attach them.
[common.pt.txt](https://github.com/Protelis/Protelis/files/3346372/common.pt.txt)
[resourcetracker.pt.txt](https://github.com/Protelis/Protelis/files/3346373/resourcetracker.pt.txt)

**Comment by DanySK** [comment]
`Infinity`, `e`, and `pi` got dropped from Protelis since we can access Java `public static` fields. Try to solve by:
```
import java.lang.Double.POSITIVE_INFINITY
```
and then replacing `Infinity` with `POSITIVE_INFINITY`. Of course you can rename it with a `let` if you find the Java wording to be too verbose. If you have `-Infinity`, you can consider using `NEGATIVE_INFINITY` in the same way.

**Comment by jschewebbn** [comment]
Thanks, that takes care of the Inifinity error. It looks to me like something else is wrong with the electLeader function. I'll work with @jakebeal  on that.

@DanySK looking at the broadcastObjectToRegion function in resourcetracker, it looks like the issue there is that I don't want the semicolon after the call to hopBroadcast. When I remove that I get errors in the function below it, computeResourceSummary. Looking at #167, I believe I just need to remove the last semicolon in a block.

**Comment by DanySK** [comment]
@jschewebbn you are absolutely right. Once you remove those two semicolons, you'll likely get more errors due to semicolons at line 160, 166, and 169.

**Comment by jschewebbn** [comment]
I'm getting much closer, now I'm stuck at line 212 in this updated version.
[resourcetracker.pt.txt](https://github.com/Protelis/Protelis/files/3346546/resourcetracker.pt.txt)

**Comment by DanySK** [comment]
Missing semicolon @218, illegal instruction @214: assignment is a side effect, and `if` when used with `else` expects an expression in both branches to be returned. This is usually an indication that we are forcing an imperative style over a functional language.
Check if you can refactor more idiomatically, e.g. from:
```
    if(self.getDevice().isUseLeaderElection()) {
        globalLeader = self.getDevice().isGlobalLeader()
    } else {
        globalLeader = electLeader();
        self.getDevice().setGlobalLeader(globalLeader)
    }
```
to
```
let device = self.getDevice();
globalLeader = if(device.isUseLeaderElection()) { device.isGlobalLeader() } else { electLeader() };
self.getDevice().setGlobalLeader(globalLeader);
```
There is actually a change in behaviour here: every devices calls `setGlobalLeader`, I'm not sure if this is problematic (depends on the specific case). In case, I can suggest another refactoring that preserves the same behaviour (but does not look as nice).

**Comment by jschewebbn** [comment]
Right, I'm thinking as an imperative programmer, thus the poor functional logic. You're refactoring is reasonable. However I think there needs to be a "let" in front of "globalLeader =".

Now the only error I have is that "electLeader()" is undefined. However I think that's due to some errors in that function that I need help from @jakebeal to resolve.

**Comment by DanySK** [comment]
OK, let me know if you can use help

**Comment by jschewebbn** [comment]
I've spent some more time on common and I've resolved the errors there. Now I've got another error in resourcetracker.pt. It's on line 240, no viable alternative at let.
[resourcetracker.pt.txt](https://github.com/Protelis/Protelis/files/3352480/resourcetracker.pt.txt)


It would also be really nice if I could tell the parser to ignore derived directories. I'm getting lots of errors about "Couldn't resolve reference to ProtelisModule ..." in my derived directories.

**Comment by jschewebbn** [comment]
I took another look this morning. It appears I'm missing a semicolon at the end of that let ... multiRegion expression.

**Comment by jschewebbn** [comment]
Still not sure why I didn't get any runtime errors when I get errors in eclipse.

**Comment by DanySK** [comment]
Ho @jschewebbn, which is the current situation with resourcetracker.pt? Did you figure it out?

About errors in Eclipse but not at runtime: they are due to misaligned versions of protelis-parser between the eclipse plugin and the runtime. You can verify this by inspecting your gradle dependencies for protelis-parser, it is likely that the version used there is older than the one in Eclipse (which takes the latest stable automatically).

**Comment by jakebeal** [comment]
Is there some way for the Eclipse plug-in to inspect the project environment and warn about version mis-matches?

**Comment by jschewebbn** [comment]
My protelis dependency in gradle is 
```
group: 'org.protelis', name: 'protelis', version:'12.1.0'
```

**Comment by jschewebbn** [comment]
And yes, I figured out the issues with resourcetracker.pt.

**Comment by DanySK** [comment]
@jakebeal there is no way that I am aware of. The plugin is generated, and we have little control over it. It would need to interact with the way eclipse deals with dependency management, which is different depending whether you are using Maven, Gradle, SBT, creating a plain Java / Scala / Kotlin project, etc. They are in fact two separate worlds: the eclipse plugin provides IDE highlighting / completion, but execution is solely dependent on what is on classpath (and rightly so, otherwise we would need an instance of Eclipse for executing).

The only sane way to check consistency would be to do it plugin-side. I don't yet know how to, though.

**Comment by jschewebbn** [comment]
@DanySK Given my gradle dependency and the latest plugin, do you believe there is a mismatch in versions?

**Comment by DanySK** [comment]
Hi @jschewebbn 
the best way to compare the versions is the following:

## For the eclipse plugin
Help -> About Eclipse IDE -> Installation Details -> Installed software -> type "protelis" as filter -> annotate the version of "Protelis Feature" (e.g. 9.1.2)
![image](https://user-images.githubusercontent.com/1991673/61720308-d39c0e00-ad66-11e9-8a14-1e810fafe200.png)


## For the actual parser being in use by Gradle / Eclipse when compiling/executing
`./gradlew dependencyInsight --dependency protelis.parser --configuration runtimeClasspath`

You should be presented something similar to

```
> Task :dependencyInsight
org.protelis:protelis.parser:9.1.2
   variant "runtime" [
      org.gradle.status                  = release (not requested)
      org.gradle.usage                   = java-runtime
      org.gradle.category                = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling     = external
         org.jetbrains.kotlin.platform.type = jvm
         org.gradle.jvm.version             = 8
   ]

org.protelis:protelis.parser:9.1.2
\--- project :protelis-interpreter
     +--- runtimeClasspath
     \--- project :protelis-lang
          \--- runtimeClasspath
```

If they have matching versions, they should raise the same errors.

**Comment by jschewebbn** [comment]
OK, so eclipse is using a newer parser than the release of Protelis that I'm using
```
org.protelis:protelis.parser:8.2.0            
   variant "runtime" [
      org.gradle.status              = release (not requested)                     
      org.gradle.usage               = java-runtime
      org.gradle.category            = library (not requested)                             
                                                                     
      Requested attributes not found in the selected variant:                                  
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]                                          
```

Will moving to 12.2.0 make them match?

**Comment by DanySK** [comment]
Depends how up to date you are with Eclipse. The Eclipse very latest plugin (9.2.1) is not yet integrated in the interpreter (I'm working on a realignment right now, but requires #75 to get fixed and requires some time).

**Comment by DanySK** [comment]
One thing we are currently missing is a P2 repository where to deploy all the plugin versions. This would allow to be at least able to sync versions manually. I currently deploy on surge.sh, maybe we could use a github repo to host artifacts and point the marketplace there, but I fear it might be in violation of GitHub TOS.

**Comment by jschewebbn** [comment]
I have plugin version 9.1.2. According to the update site this is the newest version available.

**Comment by jakebeal** [comment]
Superseded by #214 and #245
