### ISSUE TITLE
DeviceUID should not be a long

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#18]
Currently, DeviceUID has a long getId() method that is actually just an implementation detail. Removing this method will impact AbstractExecutionContext, that will switch from a TLongObjectMap to a classic Java Map.

I think that forcing a UID to be a long is quite restrictive. I'd be in favour of removing such method, and just using DeviceUID as a "marker" interface.

@jakebeal what do you think?

**Comment by jakebeal** [comment]
If you do this, I will just remove the @Overload on my getId implementations.  I think this will be OK.

**Comment by DanySK** [comment]
There is another consequence, that I guess is the reason why we have that orrible long in place. We have an implementation of Field that relies on a GNU Trove's TLongObjectMap rather than on a Java Map. This implementation is currently preferred because faster than the Java Collections couterpart.

Removing the DeviceUID / long binding would make this implementation no longer viable. I am still in favor of changing: there is a design problem here, and it should have precedence over raw performance, especially because we are not completely sure that this our bottleneck.

**Comment by jakebeal** [comment]
Can you test the performance hit and document it here?  Then we can make an informed decision.

**Comment by DanySK** [comment]
I have used this as a benchmark:
```
val x = 1

default environment
linking nodes in range 5
 
protelis program prog 
rep (r <- random) {
	mux(r < minHood(nbr(random))) {
		r
	} else {
		minHood(nbr(random))
	}
}
@x,x
  
place 100 nodes within rect (0,0,9,9) with program prog 
```

Simulating 10000 seconds of system evolution on my Intel Core i5 2500K.
The system takes ~3 seconds for setting up the simulation.

Trove field implementation:
```
RUN1: 19.144s
RUN2: 17.785s
RUN3: 18.268s
```
Collections field implementation:
```
RUN1: 15.499s
RUN2: 16.792s
RUN3: 15.997s
```

Well, this is surprising. I re-executed with the Trove implementation right after the Java Collections one, and I got 18.661s.
I'd say there is no real advantage in using Trove for this specific situation.

There would be also another change: our interfaces (and implementing classes) that expose a TLongObjectMap<Map<CodePath, Object>> would need to be changed to Map<DeviceUID, Map<CodePath, Object>>, since there is no more a mapping between DeviceUID and long.

So, resuming what we know:
Cons:
* The change would break backwards compatibility
Pros:
* Cleaner interfaces
* No more DeviceUID <-> 64bit long value equivalence
* Performance hit seems to be very small (if any)

**Comment by jakebeal** [comment]
Given there is no performance hit, looks like a net win to me.

**Comment by DanySK** [comment]
Then I am doing the change before our first release, so that interfaces won't change immediately.

**Comment by DanySK** [comment]
Related note. If we switch to a Java Map implementation, we have different Map implementations, some of them supporting concurrency. I have benchmarked them (seconds, lower is better):

* Map
    * HashMap
        * RUN1: 39.461
        * RUN2: 38.410
        * RUN3: 38.216
    * LinkedHashMap
        * RUN1: 38.867
        * RUN2: 38.602
        * RUN3: 39.280
    * TreeMap (Requires DeviceUID to be Comparable)
        * RUN1: 43.872
        * RUN2: 45.037
        * RUN3: 45.488

* ConcurrentMap
    * ConcurrentHashMap
        * RUN1: 43.789
        * RUN2: 43.410
        * RUN3: 43.484
    * ConcurrentSkipListMap (Requires DeviceUID to be Comparable)
        * RUN1: 52.724
        * RUN2: 65.359
        * RUN3: 65.561

The benchmark has been done using the current sequential operations, if we adopt a concurrent map we might have performance improvements if we use parallelism internally, but we need to declare on the Field interface that we expect implementations to be thread-safe.

Given those benchmarks, I am going for a non-concurrent implementation backed by a LinkedHashMap, that might get faster if we iterate the same field multiple times.

Let me know if you think another strategy would be better.

**Comment by jakebeal** [comment]
Field calculus has an atomic execution model, so I think that we should keep it non-concurrent.  We should add this into the JavaDoc, however.

**Comment by DanySK** [comment]
Well, that level of concurrency would be at the implementation level, besides bugs it should have no impact on atomicity of the field calculus cycle. Anyway, I have submitted a pull request with a sequential, LinkedHashMap-backed implementation for review.
