### ISSUE TITLE
NoSuchMethod error for bad function arguments is opaque

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#181]
When function calls fail with a "NoSuchMethod" exception, it is unclear whether this is because of a null, an argument mismatch, wrong data type, etc. We should have more informative exceptions.

**Comment by DanySK** [comment]
Hi Jake,
can I have some minimal examples of code generating the issue, and/or stacktraces where the problems are clearly visible? It would be helpful for addressing the issue.

**Comment by DanySK** [comment]
I believe this issue is now outdated, as the error reporting changed consistently.

**Comment by jakebeal** [comment]
I can't seem to reproduce the error, so I'm closing until it occurs again.
