### ISSUE TITLE
*PlusSelf operators do not work

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#19]
When using an "PlusSelf" operator like minHoodPlusSelf do not work: they produce a parse error.
New (failing) test Hood02 demonstrates this problem.

**Comment by DanySK** [comment]
Current syntax requires a space. The test is the problem, not the interpreter. I have updated it to work correctly.

**Comment by jakebeal** [comment]
This syntax is very non-Java-like, and should be fixed to not have a space, like it previously was.  I believe this will make the xtext formulation less elegant, since we'll need to have e.g. minHood and minHoodPlusSelf directly listed, rather than doing all of the PlusSelf together with a single element.  Still, we need to do it.

**Comment by DanySK** [comment]
I have created a new issue here: https://github.com/Protelis/Protelis-Parser/issues/6, since it is a parser issue.
