### ISSUE TITLE
Protelis can't get upgraded to Gradle 5.+, dropping Java 7?

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#195]
Our current build system needs an upgrade, as we use many deprecated features, which are by they way a possible actor in the transitive dependency issues @jschewebbn experienced in the past. However, we cannot upgrade Gradle to the 5 series, not because of any fault of ours but because of evant/gradle-retrolambda#273.

We can either wait until such bug is fixed, or drop the Java 7 build entirely. This legacy is going to be progressively harder to deal with.

**Comment by jakebeal** [comment]
@radarku : I think Java 7 was being kept for your projects?

**Comment by jakebeal** [comment]
According to @radarku , there is indeed a backward compatibility issue with the MTIP system (https://ds.bbn.technology/projects/mtip.html), but that project is over and he says it's OK to break backward compatibility: we will just have to bring things forward there in the future.

**Comment by DanySK** [comment]
The parser at version 8.2.0 still has Java 7 support, but the two builds now diverged sensibly. My proposal is to keep Java 7 support until we use that version of the parser, and drop it when further development is required.
