### ISSUE TITLE
Should share and rep align if equivalent?

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#200]
```
share(local, field <- 1) {
    minHood(nbr(local))
}
```

```
rep(local <- 1) {
    minHood(nbr(local))
}
```

Those two programs are functionally indistinguishable. Should they align?
Consequences:
* if they should (or could) align, we do not need a bytecode instruction for rep, as it is just a special case of share (as it is in the actual interpreter implementation, and in the soon-to-appear share paper, which is nice to me)
* if they must not align, we still need a rep bytecode
* due to the way anonymous functions alignment is implemented, this choice could have an impact: alignment on call of lambda functions is based on body AST analysis, as bytecode sequences are only known at runtime, so currently:
``() -> { share(local, field <- 1) { minHood(nbr(local)) }}``
is not the same as 
``() -> { rep(local <- 1) { minHood(nbr(local)) }}``

Both choices sound reasonable to me, we just need to be consistent.

This is part of #83 .

**Comment by DanySK** [comment]
@jakebeal @mviroli I'd like your opinion on the subject

**Comment by jakebeal** [comment]
I believe this depends on whether we are implementing `rep` strictly as a macro-expansion into a `share` construct. If we are, then the two will indeed not be distinguishable in the AST, and it will be correct for them to align.

If this is not the case, however, then it's OK for the two to be different even though they are functionally the same, just like `1+nbr(x)` and `nbr(x)+1` will not align even.

**Comment by mviroli** [comment]
In the papers we tend to align only syntactically equivalent programs.. so I would probably not align them

**Comment by DanySK** [comment]
I'm not letting them align, then. Thanks.
