### ISSUE TITLE
Alignment of similarly-structured lambdas

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#202]
@jakebeal @mviroli
Should the following two lambdas align?
```
let closure = 0;
() -> { nbr(closure) }
```
```
let bar = 1;
() -> { nbr(bar) }
```

Should instead these two?
``(foo) -> { nbr(foo) }``
``(bar) -> { nbr(bar) }``

How do we consider variable naming w.r.t. alignment?

**Comment by jakebeal** [comment]
I believe that neither of these should align, since the parser is retaining information such as variable names.

Thanks,
-Jake

**Comment by mviroli** [comment]
The key point is that an implementation can safely use as equation strategy anything in between "strict syntactic equality" and "same evaluation tree guaranteed". In TOCL, in particular, it was decided to use equality modulo renaming of variables, which is clearly in between the two ends above. As far as current implementation is concerned, I see only good reasons for just sticking to "strict syntactic equality".

**Comment by DanySK** [comment]
We are covered already, then.
