### ISSUE TITLE
Lighter development cycle proposal

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#211]
Hi,
I'd like to propose a change to our work pipeline in order to simplify the release process. Currently, we use a mixture of [git flow](http://archive.fo/4M9QW) and pull requests. The former way works well when multiple people, insist on the same repository. The latter works better when the team is distant in space / time and a more formal review process is required.
Since we already have the second in place, we may think of relaxing the overhead introduced by git flow by:
* working on master directly
* identifying stable versions with tags (we do this already)
* [protecting the master branch](https://help.github.com/en/articles/about-protected-branches), so that changes go through mandatory code review

Of course, on forks everyone (or every sub-team) can work as preferred.

**Comment by jakebeal** [comment]
I don't really see how this would simplify the process --- git flow seems pretty lightweight to me.

**Comment by DanySK** [comment]
One less branch (develop becomes master, master disappears). We are currently keeping two long-lived branches, but we really use only develop. And we never use feature / support / release branches.

**Comment by jakebeal** [comment]
Personally, I like the way the gitflow model keeps master very clean and sparse in its commits, since they become almost synonymous with releases.  If we aren't using feature branches, we certainly can (support and release branches are less relevant in our particular case).

**Comment by DanySK** [comment]
We rely on forks usually to develop features. Anyway, not a problem to keep on using gitflow. Closing.
