### ISSUE TITLE
Make PlusSelf syntax more Java-like

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#215]
Current PlusSelf syntax forces a space in between the hood operator name and the self-inclusion specification. This should be fixed.

**Comment by jakebeal** [comment]
Let me poll and see if this is desired or not.

**Comment by DanySK** [comment]
Likely to be tackled along with #172 and #75

**Comment by jakebeal** [comment]
Assigning back to @DanySK as something to be done as a side effect of #75

**Comment by DanySK** [comment]
Solved by #253
