### ISSUE TITLE
Missing exception for wrong reference resolution

### ISSUE THREAD

**Issue by w4bo** [Protelis/Protelis#217]
Given the following `brokenCall` module: 

```
module brokenCall
public def broken() { 
    nbr(v) 
}
```

Running this code:

```
import brokenCall
nbr(v)
```

throws:

```
java.lang.IllegalArgumentException: The Protelis program cannot be created because of the following errors:
Error, line 3: Couldn't resolve reference to EObject 'v'.
Error, line 2: Couldn't resolve reference to EObject 'v'.
```

However, running this code ([brokenCall.zip](https://github.com/Protelis/Protelis/files/558701/brokenCall.zip)):

```
import brokenCall
broken()
```

does not throw any exception.

**Comment by DanySK** [comment]
I was able to produce a case in which an obscure NullPointerException was produced when linking to a broken module. It's quite a corner case.
I intercepted the error and produced a much clearer message, which is:
```
java.lang.NullPointerException: The program usereplicatedgossip cannot be created because the required function timereplication:timeReplicated has errors in its body
	at java.util.Objects.requireNonNull(Objects.java:228)
        ...moar stacktrace
```

**Comment by jakebeal** [comment]
Is this resolved?  I don't see a link from a pull request

**Comment by DanySK** [comment]
Yes it is, if you agree the message above is clear enough

**Comment by jakebeal** [comment]
Yes, sounds good.
