### ISSUE TITLE
unionHoodPlusSelf not aligning correctly

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#229]
The unionHood operation appears to be failing to align when PlusSelf is included.

In this code:
```
    let rgn = self.getDevice().getRegionIdentifier();
    let localNbrRgns = unionHood PlusSelf(nbr([rgn]));
```
we get only the local value, and not the values of the neighbors.  This seems to indicate a failure to align, which seems likely to somehow be linked to the new bytecodes used to fix alignment.

This works in Protelis 11, but not Protelis 12.

Note that we are also running this within a multiRegion operation, so the recursion into child processes may be involved as well.

**Comment by DanySK** [comment]
Can you check if this bug also affects other hood reductions and/or non-plusself operations?

**Comment by jakebeal** [comment]
I went to go and check this out with protelis-test, and found that we are not actually testing alignment at all in protelis-test, since all of the operations are only on a single device.  Thus, it's not currently possible to know if any of the operators are working via protelis-test.

**Comment by DanySK** [comment]
This is not the case. We test alignment rather intensively in protelis-lang's tests, which run on a simulated environment

**Comment by DanySK** [comment]
protelis-test contains single device tests and (in the main source set) the testing platform code, which is used inside protelis-lang and (possibly) other projects that need to do testing with protelis.

**Comment by jakebeal** [comment]
Since protelis-test is only single-device, I think that protelis-lang needs to systematically test the hood operations.

**Comment by DanySK** [comment]
I agree.

**Comment by jakebeal** [comment]
False alarm on this bug: tracked it down to an emergent issue in our networking interface caused by the adaptations needed to upgrade to Protelis 12.  We still need the systematic testing by protelis-lang, so I'll open a new issue for that.
