### ISSUE TITLE
Auto-imports

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#243]
Hi, to solve #75 appropriately I needed to figure out how to auto-import stuff. It took me days, as it's entirely undocumented, but now automatic imports are possible. My proposal would be to automatically import:
* Either `java.lang.Math` or `org.apache.commons.math3.util.FastMath`. I'd go for the former: the second has more functions, but the former is guaranteed to be found on any JVM (performance here are not a problem they get dwarfed by the interpreter overhead anyways).
* `java.lang.Double` for easy access to `POSITIVE_INFINITY` and `NEGATIVE_INFINITY`
* `org.protelis.Builtins`, a new class to be written in the interpreter where we can add and remove builtin functions without touching anything the parser.

Other notes:
* Manual imports shadow defaults. Importing e.g. `java.lang.Integer.*` would make `MAX_VALUE` to point to `Integer.MAX_VALUE` rather than the default `Double.MAX_VALUE`. Disambiguation is possible by full names (e.g. java::lang::Double::MAX_VALUE). We may want to raise a warning in case of shadowing.

**Comment by jakebeal** [comment]
Nice work --- this sounds like an excellent approach, and I endorse all of your proposals.

**Comment by DanySK** [comment]
PR Protelis/Protelis-Parser#25 implements the changes listed above in the parser.

**Comment by DanySK** [comment]
Issue will be closed with #75

**Comment by DanySK** [comment]
Solved by #253
