### ISSUE TITLE
Eclipse plugin version skew from Protelis library

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#245]
We get lots of errors when the Eclipse Protelis parser plugin does not match the version of Protelis actually being used in a project.  

Can we have the Eclipse plugin be version aware, such that it can either maintain multiple versions and pick the right one or at least give the user one error of version mismatch rather than hundreds of errors when it disagrees about syntax?

**Comment by jakebeal** [comment]
Since the plugin can't actually example the project, let's address this by having the plugin report its protelis version in the errors that it supplies.

**Comment by DanySK** [comment]
I believe I found an acceptable workaround: the plugin looks for the builtins to be an interpreter-defined class. We may include version information there (ideally should be injected by the build system), and look for it in the plugin.

**Comment by DanySK** [comment]
Fixed in [13.1.0](https://github.com/Protelis/Protelis/releases/tag/13.1.0)
