### ISSUE TITLE
Short function definition

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#252]
Modern JVM languages allow a short syntax for single-expression methods. Protelis should be able to do it as well, e.g.:
```
def inc(a) {
  a + 1
} // previous syntax, still supported

def shortInc(a) = a + 1 // much more compact
```

**Comment by metaphori** [comment]
@DanySK OT: these changes may break ProtelisDoc. We should find a strategy for dealing with it: e.g., supporting multiple versions of protelis in same plugin, updating plugin, etc.

**Comment by DanySK** [comment]
How hard would it be to support the new syntax? My supposition would be that it should be reasonably easy (match def, match what comes first between `{` and `=`, what I'm missing?)

Your idea is very nice, but till we are so alpha, I'd just focus on the latest stable Protelis

**Comment by DanySK** [comment]
Changes have been introduced by #253
