### ISSUE TITLE
Document how to generate Protelis Dokka/JavaDoc

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#258]
Following #256 and https://github.com/map-dcomp/P2Protelis/pull/3, it appears that using Dokka/JavaDoc for protelis is non-trivial to set up.

We need to have documentation in the Protelis README that explains how to add documentation generation for new projects.

**Comment by metaphori** [comment]
@jakebeal I would essentially add to Protelis README a link to [Protelis-KDoc-generator plugin](https://github.com/Protelis/Protelis-KDoc-generator) README, with an explaining sentence, so as to simplify the maintenance of docs by reducing the need of keeping them synchronised. Would it be ok?

**Comment by jakebeal** [comment]
That sounds reasonable.  Once you've done that, let's test how hard it is to install by having me try to apply it to a new project.

**Comment by metaphori** [comment]
This should be fixed by PR #259
