### ISSUE TITLE
Make sure Eclipse plugin autocompletion can help with Protelis imports

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#32]
Protelis imports are a pain to do compared to Java imports in Eclipse.
I think the Xtext-based Protelis plugin should be able to support autocompletion for Protelis as well: let's see if we can make that happen.

**Comment by DanySK** [comment]
Please check out the latest version, this should be now fixed (or improved at least).

**Comment by jakebeal** [comment]
Need to check if it's working with the current system.

**Comment by jakebeal** [comment]
Checked, and it's working.
