### ISSUE TITLE
Add tests of error-handling

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#34]
Our error messages aren't very good, and we need tests that make sure that reasonable things are being said when programs fail to parse correctly.

**Comment by DanySK** [comment]
This goes along with #169. The clarified messages now have tests in place.
My position here would be to have a change in methodology: every time we close a bug report about unclear errors, we also add a test.

If you agree, I think we can close this issue.

**Comment by jakebeal** [comment]
Let's close this one as duplicate, but keep #169 open for now.  I think I'd like to have a general review of all error messages at some point.
