### ISSUE TITLE
rep does not check whether variables are defined; variables are in fact not generally checked

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#36]
When one writes:

>  rep(x <- nonsense) { x }

with "nonsense" not defined, it should be a cross-reference parse error; instead, rep just returns false.

**Comment by jakebeal** [comment]
Test added in branch at https://github.com/jakebeal/Protelis/commit/a802b352ae574300bcb861bed8b952caa65a4cc9

**Comment by DanySK** [comment]
With the self.getEnvironmentVariable() mechanism in place, we should do so for all the variables. By the way, I think it is a parser issue.

**Comment by jakebeal** [comment]
I'm pretty sure that this is a parser issue, which is why I assigned it to you...

I'm not sure what you mean by "do so for all variables," though: environment variables are globals, and so serve a different purpose than other variables.

**Comment by DanySK** [comment]
I mean that currently if you write:
```
foo
```
as a program it throws no errors at compile time, even though foo was not defined anywhere. So the same check that must be done for ```rep```s should be actually done for any variable of a program.

**Comment by jakebeal** [comment]
Crap: you are totally correct.  I've added a new testVariable into the failure branch that checks this failure mode.

**Comment by DanySK** [comment]
A parser version that implements the required check has been pushed [here](https://github.com/DanySK/alchemist-protelis-parser/commit/b4bf1ed11f674e67c60015df1e39c46591b60823).

**Comment by DanySK** [comment]
This is solved now
