### ISSUE TITLE
Check whether Java/Oracle recommends block comments in // or /* */

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#43]
We should be consistent and follow recommended best-practices in how we do our multiline block comments.

**Comment by DanySK** [comment]
Document from Oracle (to be read): http://www.oracle.com/technetwork/java/codeconventions-141999.html#385

**Comment by jakebeal** [comment]
Looks like Sun disapproved of using // for multi-line comments in 1999, but more recently many seem to prefer them (e.g., [this well-reasoned article](http://javadude.com/articles/comments.html) and [this StackOverflow answer](http://stackoverflow.com/questions/1085364/why-is-style-multiline-comment-bad-in-java)).

There's no clear consensus on either side, however, and so I think we can simply ignore this issue.

**Comment by DanySK** [comment]
I think it really comes down to which editor the developer uses. Eclipse, for instance, makes it very easy to use single line comments on multiple line selection for quickly cutting off portions of code (on Linux is ctrl+shit+7), so the "I cannot type */ after a multiline comment is not really an issue.

I think I will personally use block-style always from now on, unless I need to cut off portions of code, reason being:
* Consistency with the style of Javadoc
*  Easier to add text

But I totally agree that we should not enforce any rule on that matter.
