### ISSUE TITLE
Current syntax for hood operations

### ISSUE THREAD

**Issue by zajer** [Protelis/Protelis#440]
When I try to use `minHood` operation with a single argument (as defined in https://github.com/AlchemistSimulator/SASO17Tutorial ) I get a warning about deprecated hardcoded hood operation. 
Sadly the in tutorial available here:
https://github.com/AlchemistSimulator/Protelis-Incarnation-tutorial
it is invoked the same way.

As suggested, I have read the discussion on #75 but still can't figure out how am I suppose to invoke this function to get rid of the above warning.
I have tried `minHood( default_val, field2reduce)` with reversed order of arguments but neither of them works.

**Comment by DanySK** [comment]
Hi @zajer 
the new set of builtin field reduction operations are `fold` (requiring base values and falling back to the local field value if none is provided) and `reduce` (producing `Option`s). I believe that in your case a fold operation is what you desire.

Try [`foldMin(minHood(default_val, field2reduce)`](https://github.com/Protelis/Protelis/blob/f14a0c8df8c0e277b9eac1c132cea6a4042673c6/protelis/protelis-interpreter/src/main/java/org/protelis/Builtins.java#L206-L220).

This will *discard the local field value* and find the min in the neighborhood using `default_val` as base.
Is that what you need?

**Comment by zajer** [comment]
Yes! Thank you very much.
