### ISSUE TITLE
ProtelisAST implementations should expose their fields

### ISSUE THREAD

**Issue by aPlacuzzi** [Protelis/Protelis#457]
Hi all,
I need to estimate the complexity of a Protelis program.
Actually, I navigate all the AST and I assign a weight to each node considering only the instruction type,
and not all the information of the AST node.
For example, I can't take into account the field `left` of the `Invoke` instruction.
So, the result is only a very approximate estimation.

I would like to ask if it is possible to add getters to the Protelis instruction classes (`Invoke`, `FunctionCall`, and so on) to have read-only access to their private fields

**Comment by DanySK** [comment]
Since the AST structure is immutable starting with version 14.0.0, this is actually a reasonable request, and it is not hard to implement. I see it can be useful for a number of "reflection-like" and inspection tasks.
Unless @jakebeal sees any issue, I'd go forward and implement it. Jake?

**Comment by jakebeal** [comment]
I don't see any problem either. This will add a bit of complexity to the storage of a Protelis program in memory, but shouldn't impede normal execution in any way.

**Comment by DanySK** [comment]
There should be no relevant issue with memory use either, as [methods are defined in classes, which are singletons, while instances size only depends on fields](https://stackoverflow.com/questions/2935815/does-having-more-methods-in-a-class-mean-that-object-uses-more-memory-at-runtime#:~:text=So%20a%20class%20with%20more,have%20the%20same%20data%20members.).
