### ISSUE TITLE
Add line length check to checkstyle

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#47]
Make sure that CheckStyle warns for lines longer than 120 characters.

**Comment by jakebeal** [comment]
Eh, I don't think this is actually important.

**Comment by DanySK** [comment]
Hi, it is an easy thing to do. Moreover, let me hijack this thread: running through [the Java Code Conventions](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf)
I have discovered that our indenting is against recommendation (four spaces, no tabs). I have already worked out a rule for both those things that helps me prepare code to give to students. I could easily import them in Protelis too.

**Comment by DanySK** [comment]
The new style file is checked in already
