### ISSUE TITLE
Allowing Kotlin code in Protelis

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#621]
This question is mostly for @jakebeal.
I think that we should allow Kotlin code to co-exist with Java code in Protelis, slowly migrating to Kotlin as new components get created.

Kotlin is a Java-compatible modern language that is gaining a lot of traction after Google picked it as the choice for Android, [replacing Java](https://developer.android.com/kotlin/first).
Learning Kotlin is reasonably easy for Java programmers, one quick way is by solving the [Kotlin Koans Online](https://play.kotlinlang.org/koans/overview).
Of course, it takes more time to get the nuances of the language and to write idiomatic code, but developers can get productive in a short time.

I am personally adopting Kotlin in every project I maintain (including [Alchemist](https://alchemistsimulator.github.io/)).
In my experience, it indeed slashes the maintenance effort consistently.

On a related note, since Protelis interoperates with Java and Kotlin is fully Java-interoperable, in all my recent experiments when I had to write Java components I actually wrote them in Kotlin, and called Kotlin code from Protelis and vice-versa with no problem and no changes (we can safely say that Protelis is already Kotlin-interoperable).

This issue is to ask whether you agree to allow Kotlin code inside the Protelis code base. We won't replace the existing Java code at once (that would be a cost with no immediate benefit), but new code, or large refactorings, are allowed to use Kotlin alongside Java.

**Comment by jakebeal** [comment]
Given that the two are interoperable, I have no objection.

**Comment by DanySK** [comment]
Grand.
