### ISSUE TITLE
Get JavaDocs into published distribution

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#68]
When using Gradle/Maven/etc to pull a distribution from the Central Repository, no JavaDocs are currently included.  This makes development in Eclipse much more inconvenient than it ought to be.

**Comment by jakebeal** [comment]
Note that this bug may not be visible unless you use an Eclipse workspace without the Protelis project, since Eclipse is smart and will attempt to connect to the live project rather than pulling from the Central Repository.

**Comment by DanySK** [comment]
It is not really possible to commit stuff on Central without the any javadoc attached. If you configured Gradle to pull org.protelis:protelis, have you properly configured it to also pull documentation?

Look at lines 134:141 of https://github.com/Protelis/Protelis/blob/master/build.gradle.
These lines also pull sources and javadoc from a Maven repository, and make them accessible to Eclipse. Do you have such configuration in your build.gradle?

**Comment by jakebeal** [comment]
I'm building with Maven... and now that I know that the documentation is there on Central, I was able to put together the correct set of keywords and search out a solution.  In short, I needed to set "downloadSources" and "downloadJavadocs" to true in my maven pom.xml file.

**Comment by DanySK** [comment]
Removed the bug label to remove this issue from the solved bugs list
