### ISSUE TITLE
drone.io builds failing

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#70]
We're getting a *lot* of weird build failures on drone.io right now.  The main categories seem to be:

* Failure to do *anything* --- build has a timestamp of "0001-01-01 00:00:00 +0000 UTC"
* Out of time errors

Can we do anything about this?

**Comment by DanySK** [comment]
Partly. Some errors I don't understand - the ones with the absurd timestamp, and I need some time to look through them. I believe they are not a mistake of us.

Some other instead seem to be the nightly builds trying to build also the `develop` branch, which does not currently exists.
If we agree that [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) is a branching model that we should use (and I advocate so), still continuing to keep our forks separated for higher cleanliness, then I propose to create the develop branch where missing.

Also many Alchemist packages are failing for this reason, and I'm going to fix them this way.

**Comment by jakebeal** [comment]
The busted timestamps have gotten sorted out; I wrote to drone.io tech support, and it turned out we'd gotten hosted on a busted instance of some sort.
