### ISSUE TITLE
Protelis tuples should be rolled back from Java8 to Java7 dependencies.

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#90]
At some point, Tuples started requiring Java8, which I do not believe is necessary.  This means I can't link in a Java7 environment, which means I'm currently stuck at Protelis 5.0 on MTIP.

**Comment by DanySK** [comment]
Retrolambda appears to be still on its place, and I can find no reference to Java 8 libraries. Please note that java8.util package is the Streamsupport Java 7 backport of Java 8's new collection libraries.
I am running now a build on drone, I will inspect the generated bytecode to make sure it's Java 7 compatible.

**Comment by DanySK** [comment]
Build [782](https://drone.io/github.com/Protelis/Protelis/782) completed successfully, this is the analysis on the generated artifacts. I downloaded them, then unpacked, then disassembled to check the version.

Major version 51 -> Java 7
Major version 52 -> Java 8

```bash
danysk@latitude ~/Downloads/protelis-9.0.0/org/protelis/lang/datatype $ javap -v Tuple | grep major
Warning: Binary file Tuple contains org.protelis.lang.datatype.Tuple
  major version: 51
```

```bash
danysk@latitude ~/Downloads/protelis-9.0.0/org/protelis/lang/datatype $ javap -v Tuples | grep major
Warning: Binary file Tuples contains org.protelis.lang.datatype.Tuples
  major version: 51
```

```bash
danysk@latitude ~/Downloads/protelis-9.0.0/org/protelis/lang/datatype $ ls impl/ArrayTupleImpl*
impl/ArrayTupleImpl.class               'impl/ArrayTupleImpl$$Lambda$4.class'  'impl/ArrayTupleImpl$$Lambda$7.class'
'impl/ArrayTupleImpl$$Lambda$10.class'  'impl/ArrayTupleImpl$$Lambda$5.class'  'impl/ArrayTupleImpl$$Lambda$8.class'
'impl/ArrayTupleImpl$$Lambda$2.class'   'impl/ArrayTupleImpl$$Lambda$6.class'  'impl/ArrayTupleImpl$$Lambda$9.class'
danysk@latitude ~/Downloads/protelis-9.0.0/org/protelis/lang/datatype $ javap -v impl/ArrayTupleImpl* | grep major
  major version: 51
  major version: 51
  major version: 51
  major version: 51
  major version: 51
  major version: 51
  major version: 51
  major version: 51
  major version: 51
```

Everythings Java 7, as expected. Could you help me reproduce the issue.

**Comment by jakebeal** [comment]
Sure: first of all, I'm starting with protelis-redist-8.0.3.jar rather than 9.0.0 because this needs to be integrated into a project that can't use Maven/Gradle-style build automation (see also issue #89).  Instead, everything needs to be wrapped up in jars.

My guess is that the backport library didn't get rolled into the redist jar?

**Comment by DanySK** [comment]
No, it does. I have just downloaded the 8.0.3 version available on git
```bash
danysk@apice-workstation ~/Downloads/protelis-redist-8.0.3/org/protelis/lang/datatype $ javap -v Tuple | grep major
Warning: Binary file Tuple contains org.protelis.lang.datatype.Tuple
  major version: 51
```
The same holds for the other commands listed above.

What error do you get when trying to use this artifact on Java 7?

**Comment by jakebeal** [comment]
I've figured out the problem: it wasn't actually the library, but how I was using it.  I had a mismatch in my imports.  The 9.0.0 artifact (which is what I'm now using) works fine with Java 7.
