### ISSUE TITLE
Concept of "position" is missing in ExecutionEnvironment

### ISSUE THREAD

**Issue by w4bo** [Protelis/Protelis#92]
I am writing a JUnit test for the "distanceTo" function. Such function depends on a concept of "position" that is missing in the ExecutionEnvironment interface. Although it is possible to extend environments, tests should not be based on ad-hoc solutions.

**Comment by jakebeal** [comment]
The answer to this is going to be to create another interface, e.g., "SpatiallyEmbeddedDevice", that makes available a collection of standard functions of this sort.  What exactly goes in there is one of the things we need to figure out over the next couple of months.

**Comment by DanySK** [comment]
I agree with Jake. I'd say `SpatiallyEmbeddedDevice` should be a sub-interface of `ExecutionContext`, so that, where available, we can invoke `self.nbrRange()` and similar.

**Comment by DanySK** [comment]
This is solved.
